import './globals.css'
import type { Metadata } from 'next'
import { VT323 } from 'next/font/google'

const vt323 = VT323({ subsets: ['latin'], weight:'400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={vt323.className}>{children}</body>
    </html>
  )
}
